name = "insighthunter-analytics"
main = "index-ai.js"
compatibility_date = "2024-01-15"

routes = [
  { pattern = "api.insighthunter.app/api/forecast/*", zone_name = "insighthunter.app" },
  { pattern = "api.insighthunter.app/api/insights/*", zone_name = "insighthunter.app" },
  { pattern = "api.insighthunter.app/api/dashboard/*", zone_name = "insighthunter.app" }
]

[[d1_databases]]
binding = "DB"
database_name = "insighthunter"
database_id = "your-d1-database-id"

[[kv_namespaces]]
binding = "KV"
id = "your-kv-namespace-id"

[[vectorize]]
binding = "VECTORIZE"
index_name = "transaction-search"

[ai]
binding = "AI"

[vars]
NODE_ENV = "production"
API_VERSION = "v3"
