name = "insighthunter-ingest"
main = "index-ai.js"
compatibility_date = "2024-01-15"
type = "javascript"
account_id = "env.CLOUDFLARE_ACCOUNT_ID"
workers_dev = true

routes = [
  { pattern = "api.insighthunter.app/api/upload", zone_name = "insighthunter.app" },
  { pattern = "api.insighthunter.app/api/transactions/*", zone_name = "insighthunter.app" }
]

[[d1_databases]]
binding = "DB"
database_name = "insighthunter"
database_id = "env.D1DATABASE_ID"

[[kv_namespaces]]
binding = "CACHE"
id = "env.KV_NAMESPACE_ID"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "insighthunter-files"

[[vectorize]]
binding = "VECTORIZE"
index_name = "transaction-search"

[ai]
binding = "AI"

[vars]
NODE_ENV = "production"
API_VERSION = "v3"





