[env.production]
name = "insighthunter-api"
main = "backend/workers/main.js"
compatibility_date = "2024-01-01"
workers_dev = false
route = "api.insighthunter.app/*"

[[d1_databases]]
binding = "DB"
database_name = "insighthunter"
database_id = "your-database-id"

[[r2_buckets]]
binding = "REPORTS_BUCKET"
bucket_name = "insighthunter-reports"

[[durable_objects.bindings]]
name = "CASH_FLOW_SESSION"
class_name = "CashFlowSession"
script_name = "insighthunter-api"

[triggers]
crons = [
"0 8 * * 1",
"0 8 1 * *",
"0 */1 * * *"
]
