name = "insight-hunter-api"
main = "src/index.ts"
compatibility_date = "2025-09-26"
type = "modules"


[ai]
binding = "AI"

# Environment variables
[vars]
JWT_SECRET = "8cb92eb311e1a8106f160b01da419580707c8e5b225917dccdc5b211595f76cfe6c12c26ae9aa3859d358ea7a18183b6209673c9bbc90596d516e0a55b575f79"

# D1 Database binding
[[d1_databases]]
binding = "USERS_DB"
database_name = "insight_hunter_v2"
database_id = "708836ad-602f-4f95-a6b5-cd31a7cd188d"  

# R2 Bucket binding
[[r2_buckets]]
binding = "FILES_BUCKET"
bucket_name = "insight-hunter-files"
preview_bucket_name = "insight-hunter-files-preview"

# Optional: Dev server settings
[dev]
ip = "127.0.0.1"
port = 8787
local_protocol = "http"

name = "backend"
type = "javascript"
project_name = "backend"
account_id = "18c8e61a3669253dcfd0c7eec6be36a3"

[build]
command = "npm run build"
directory = "dist"

# Environments
[env.dev]
project_name = "insight-hunter-frontend-dev"
directory = "dist"

[env.prod]
project_name = "insight-hunter-frontend-prod"
directory = "dist"

[env]
project_name = "insighthunt-v3"
directory = "worker"

# Binding

[[D1Database]]

binding = "USERS_DB"
database_name = "insight-hunter-v2"
database_ID = "708836ad-602f-4f95-a6b5-cd31a7cd188d"

[[kv_namespaces]]
binding = "ONBOARDING_KV"
id = "74916a9faa9c4ac3be904de8b86359ae"               
preview_id = "ONBOARDING_KV"
