name = "insight-hunter-backend"
main = "./dist/index.js"
compatibility_date = "2025-09-24"

# Default build command
[build]
command = "npm run build"

# Environments
[env.dev]
name = "insight-hunter-backend-dev"
main = "./dist/index.js"

[env.prod]
name = "insight-hunter-backend-prod"
main = "./dist/index.js"
