name = "insight-hunter-backend"
main = "./insight-hunter-backend/dist/index.js"
compatibility_date = "2025-09-24"

# Default build config
[build]
command = "npm run build:backend"

# Environments
[env.dev]
name = "insight-hunter-backend-dev"
main = "./insight-hunter-backend/dist/index.js"

[env.prod]
name = "insight-hunter-backend-prod"
main = "./insight-hunter-backend/dist/index.js"

[[d1_databases]]
binding = "USERS_DB"
database_name = "insight-hunter-v2"
database_id = "708836ad-602f-4f95-a6b5-cd31a7cd188d"
 
