name = "insight-hunter-api"
main = "src/index.ts"
compatibility_date = "2025-09-23"
type = "javascript"

[vars]
JWT_SECRET = "env.JWT_SECRET"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[env.production]
workers_dev = false
route = "insight.hunterturner.com/*"
zone_id = "hunterturner.com"

[[d1_databases]]
binding = "USERS_DB"
database_name = "insight-hunter-v2"
database_id = "708836ad-602f-4f95-a6b5-cd31a7cd188d"
 
