name = "insighthunter-auth"
type = "javascript"

account_id = "./../../.dev.vars.CLOUDFLARE_ACCOUNT_ID"
workers_dev = true
compatibility_date = "2025-10-14"

main = "index-cloudflare.js"

[env.production]
name = "insighthunter-auth"
routes = ["https://api.insighthunter.app/auth/*"]

[[kv_namespaces]]
binding = "CACHE"
id = "./../../.dev.vars.KV_NAMESPACE_ID"

[[services.d1_databases]]
binding = "DB"
database_name = "insighthunter-production"
database_id = "./../../.dev.vars.D1DATABASE_ID"

routes = [
  { pattern = "api.insighthunter.app/auth/*", zone_name = "insighthunter.app" }
]

[vars]
NODE_ENV = "production"
API_VERSION = "v3"
JWT_SECRET = "./../../.dev.vars.JWT_SECRET"
