name = "insighthunter-auth"
main = "index-cloudflare.js"
compatibility_date = "2024-01-15"

#routes = [
 # { pattern = "api.insighthunter.app/auth/*", zone_name = "insighthunter.app" }
#]

[[d1_databases]]
binding = "DB"
database_name = "insighthunter"
database_id = "your-d1-database-id"

[[kv_namespaces]]
binding = "KV"
id = "your-kv-namespace-id"

[vars]
NODE_ENV = "production"
API_VERSION = "v1"
JWT_SECRET = "your-jwt-secret"
