import { env } from "./.dev.vars"

name = "insighthunter-auth"
type = "javascript"

account_id = "env.CLOUDFLARE_ACCOUNT_ID"
workers_dev = true
compatibility_date = "2025-10-14"

main = "./src/index.js"

[env.production]
name = "insighthunter-auth"
routes = ["https://api.insighthunter.app/auth/*"]

# e.g. KV
[[kv_namespaces]]
binding = "CACHE"
id = "env.KV_NAMESPACE_ID"


[[services.d1_databases]]
binding = "DB"
database_name = "insighthunter-production"
database_id = "env.D1DATABASE_ID"